### ISSUE TITLE
Got an exception while creating a TFGraph()

### ISSUE THREAD

**Issue by axeldomingues** [migueldeicaza/TensorFlowSharp#269]
Any help?

Thanks

System.BadImageFormatException
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Source=TensorFlowSharp
  StackTrace:
   at TensorFlow.TFGraph.TF_NewGraph()
   at TensorFlow.TFGraph..ctor()
   at TestTensorflow.Program.Main(String[] args) in C:\Users\adomingues\Documents\Visual Studio 2017\Projects\TestTensorflow\TestTensorflow\Program.cs:line 37

**Comment by alex-zu** [comment]
libtensorflow.dll from nuget version 1.7.0 is x64, check target OS and your assembly platform type - it must be x64

**Comment by Veroni4ka** [comment]
@alex-zu any special set up for Xamarin.Android app? Can't get rid of the dll error

**Comment by Veroni4ka** [comment]
Didn't want to bug @migueldeicaza too much, but I guess I have to. If you can provide any information about fixing libtensorflow.dll error in Xamarin.Android app, please let me know (I have the latest visual studio and xamarin)

**Comment by migueldeicaza** [comment]
Hello - TensorFlowSharp is not tested or developed against mobile.

For Android, you want to use TensorFlowLite, and I have not yet looked at what is involved.
