### ISSUE TITLE
Exception:"The object was disposed" during TFSession.Runner.Run()

### ISSUE THREAD

**Issue by tengfly** [migueldeicaza/TensorFlowSharp#382]
**Describe the bug**
First of all, I replaced the original libtensorflow.dll with a GPU version, and it runs well in some machines, but not work in one machine with Titan Xp.  Though I don't think it is caused by the difference of GPU, but I can not find out the root cause.
Code is like this:

                var tensor = new TFTensor(content);
                var image_height = new TFTensor(height);
                var image_width = new TFTensor(width);

                var runner = _session_scale.GetRunner();
                runner.AddInput(_input_scale, tensor);
                runner.AddInput(_image_height_scale, image_height);
                runner.AddInput(_image_width_scale, image_width);
                runner.Fetch(_output_scale, _scale);

                var scaled = runner.Run();
                return scaled;

When I run this code in a machine with Titan Xp, it threw the exception: "The Object was disposed."
But When I run this code in machine with K80, no problem.
The exception is like this:
Object name:“The object was disposed”。
   at TensorFlow.TFDisposable.ObjectDisposedException()
   at TensorFlow.TFSession.Run(TFOutput[] inputs, TFTensor[] inputValues, TFOutput[] outputs, TFOperation[] targetOpers, TFBuffer runMetadata, TFBuffer runOptions, TFStatus status)
   at TensorFlow.TFSession.Runner.Run(TFStatus status)
   at ExampleCommon.ImageUtil.CreateTensorFromScaledImage(Byte[,,] content, Int32 height, Int32 width)
   at TFObjectDetection.TFObjectDetector.detect(List`1 data, Single confidence_threshold)
   at TF.ImageModels.ObjectDetector.Detect(List`1 image)
   at ObjectTrackDemo.Program.<>c__DisplayClass22_0.<MultiModelDetect>b__0(ObjectDetector detector) 位置 C:\keche\XiaoiceSense\private\Src\XiaoiceSense\ObjectDetection\ObjectDetectWrapper\ObjectTrackDemo_tf\Program.cs:行号 314
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

Thanks in advance for any help.

**Comment by tengfly** [comment]
I have found out the root cause. The GPU driver of the Titan Xp machine is the version of two years ago and can not support the new CUDA driver (CUDA 9.2 in my case). So update the GPU driver fix the problem.
