### ISSUE TITLE
AccessViolationException when running LowLevelTests for SampleTest

### ISSUE THREAD

**Issue by BrianAnsems** [migueldeicaza/TensorFlowSharp#386]
* when running SampleTest, receiving following exception:
```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```
* getting this when at line 189 of LowLevelTests.cs:
```
			public void Init (int ninputs, TFGraph.WhileConstructor constructor)
			{
				inputs = new TFOutput [ninputs];
				for (int i = 0; i < ninputs; ++i)
					inputs [i] = graph.Placeholder (TFDataType.Int32, operName: "p" + i);

				Assert (status);
				outputs = graph.While (inputs, constructor, status);
				Assert (status);
			}
```
*  Anything I might be doing incorrectly?

**Comment by patrickmurray18** [comment]
Not sure if this is the same issue, but I also transiently get this error, which frankly looks like a problem with TensorflowSharp:

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at TensorFlow.TFTensor.FetchJaggedArray(Type t, TFDataType dt, IntPtr& data, Int64[] shape, Int32 level)
   at TensorFlow.TFTensor.FetchJaggedArray(Type t, TFDataType dt, IntPtr& data, Int64[] shape, Int32 level)
   at TensorFlow.TFTensor.FetchJaggedArray(Type t, TFDataType dt, IntPtr& data, Int64[] shape, Int32 level)
   at TensorFlow.TFTensor.GetValue(Boolean jagged)
```
