### ISSUE TITLE
Update to 13.1 and CUDA 10

### ISSUE THREAD

**Issue by turowicz** [migueldeicaza/TensorFlowSharp#415]
I'm having a problem when trying to run a Ubuntu+GPU solution with TensorflowSharp. 

Currently it's wrapping around `libtensorflow.so` v1.12.0 which was built with `CUDA 9`. All my machines are running `CUDA 10` and I'm unable to run TensorflowSharp, because the old `.so` file is trying to find `CUDA 9` dependencies in runtime.

**Describe the solution you'd like**
Update the wrapper to use `libtensorflow.so` v1.13.1

**Describe alternatives you've considered**
Dropping TensorflowSharp - but I don't want to!

**Comment by turowicz** [comment]
Log

```
         8:     find library=libtensorflow_framework.so [0]; searching
         8:      search path=/app/runtimes/linux/native:../local_config_cuda/cuda/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/lib64/tls/haswell:../local_config_cuda/cuda/lib64/tls/x86_64:../local_config_cuda/cuda/lib64/tls:../local_config_cuda/cuda/lib64/haswell/x86_64:../local_config_cuda/cuda/lib64/haswell:../local_config_cuda/cuda/lib64/x86_64:../local_config_cuda/cuda/lib64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64         (RPATH from file /app/runtimes/linux/native/libtensorflow.so)
         8:       trying file=/app/runtimes/linux/native/libtensorflow_framework.so
         8:
         8:     find library=libcublas.so.9.0 [0]; searching
         8:      search path=/app/runtimes/linux/native:../local_config_cuda/cuda/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/lib64/tls/haswell:../local_config_cuda/cuda/lib64/tls/x86_64:../local_config_cuda/cuda/lib64/tls:../local_config_cuda/cuda/lib64/haswell/x86_64:../local_config_cuda/cuda/lib64/haswell:../local_config_cuda/cuda/lib64/x86_64:../local_config_cuda/cuda/lib64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64         (RPATH from file /app/runtimes/linux/native/libtensorflow.so)
         8:       trying file=/app/runtimes/linux/native/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/libcublas.so.9.0
         8:      search path=/usr/local/cuda-10.0/lib64         (LD_LIBRARY_PATH)
         8:       trying file=/usr/local/cuda-10.0/lib64/libcublas.so.9.0
         8:      search cache=/etc/ld.so.cache
         8:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
         8:       trying file=/lib/x86_64-linux-gnu/libcublas.so.9.0
         8:       trying file=/usr/lib/x86_64-linux-gnu/libcublas.so.9.0
         8:       trying file=/lib/libcublas.so.9.0
         8:       trying file=/usr/lib/libcublas.so.9.0
         8:
         8:     find library=libtensorflow.so [0]; searching
         8:      search path=/usr/local/cuda-10.0/lib64         (LD_LIBRARY_PATH)
         8:       trying file=/usr/local/cuda-10.0/lib64/libtensorflow.so
         8:      search cache=/etc/ld.so.cache
         8:       trying file=/usr/local/lib/libtensorflow.so
         8:
         8:     find library=libtensorflow_framework.so [0]; searching
         8:      search path=           (RPATH from file /usr/local/lib/libtensorflow.so)
         8:      search path=/usr/local/lib             (RUNPATH from file /usr/local/lib/libopencv_stitching.so.3.4)
         8:       trying file=/usr/local/lib/libtensorflow_framework.so
         8:
         8:     find library=libcublas.so.9.0 [0]; searching
         8:      search path=           (RPATH from file /usr/local/lib/libtensorflow.so)
         8:      search path=/usr/local/lib             (RUNPATH from file /usr/local/lib/libopencv_stitching.so.3.4)
         8:       trying file=/usr/local/lib/libcublas.so.9.0
         8:      search path=../local_config_cuda/cuda/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/lib64/tls/haswell:../local_config_cuda/cuda/lib64/tls/x86_64:../local_config_cuda/cuda/lib64/tls:../local_config_cuda/cuda/lib64/haswell/x86_64:../local_config_cuda/cuda/lib64/haswell:../local_config_cuda/cuda/lib64/x86_64:../local_config_cuda/cuda/lib64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64            (RPATH from file /app/runtimes/linux/native/libtensorflow.so)
         8:       trying file=../local_config_cuda/cuda/lib64/tls/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/libcublas.so.9.0
         8:      search path=/usr/local/cuda-10.0/lib64         (LD_LIBRARY_PATH)
         8:       trying file=/usr/local/cuda-10.0/lib64/libcublas.so.9.0
         8:      search cache=/etc/ld.so.cache
         8:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
         8:       trying file=/lib/x86_64-linux-gnu/libcublas.so.9.0
         8:       trying file=/usr/lib/x86_64-linux-gnu/libcublas.so.9.0
         8:       trying file=/lib/libcublas.so.9.0
         8:       trying file=/usr/lib/libcublas.so.9.0
         8:
         8:     find library=libtensorflow_framework.so [0]; searching
         8:      search path=/app/runtimes/linux/native:../local_config_cuda/cuda/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/lib64/tls/haswell:../local_config_cuda/cuda/lib64/tls/x86_64:../local_config_cuda/cuda/lib64/tls:../local_config_cuda/cuda/lib64/haswell/x86_64:../local_config_cuda/cuda/lib64/haswell:../local_config_cuda/cuda/lib64/x86_64:../local_config_cuda/cuda/lib64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64         (RPATH from file /app/runtimes/linux/native/libtensorflow.so)
         8:       trying file=/app/runtimes/linux/native/libtensorflow_framework.so
         8:
         8:     find library=libcublas.so.9.0 [0]; searching
         8:      search path=/app/runtimes/linux/native:../local_config_cuda/cuda/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/lib64/tls/haswell:../local_config_cuda/cuda/lib64/tls/x86_64:../local_config_cuda/cuda/lib64/tls:../local_config_cuda/cuda/lib64/haswell/x86_64:../local_config_cuda/cuda/lib64/haswell:../local_config_cuda/cuda/lib64/x86_64:../local_config_cuda/cuda/lib64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64         (RPATH from file /app/runtimes/linux/native/libtensorflow.so)
         8:       trying file=/app/runtimes/linux/native/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/libcublas.so.9.0
         8:      search path=/usr/local/cuda-10.0/lib64         (LD_LIBRARY_PATH)
         8:       trying file=/usr/local/cuda-10.0/lib64/libcublas.so.9.0
         8:      search cache=/etc/ld.so.cache
         8:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
         8:       trying file=/lib/x86_64-linux-gnu/libcublas.so.9.0
         8:       trying file=/usr/lib/x86_64-linux-gnu/libcublas.so.9.0
         8:       trying file=/lib/libcublas.so.9.0
         8:       trying file=/usr/lib/libcublas.so.9.0
         8:
         8:     find library=liblibtensorflow.so [0]; searching
         8:      search path=/usr/local/cuda-10.0/lib64         (LD_LIBRARY_PATH)
         8:       trying file=/usr/local/cuda-10.0/lib64/liblibtensorflow.so
         8:      search cache=/etc/ld.so.cache
         8:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
         8:       trying file=/lib/x86_64-linux-gnu/liblibtensorflow.so
         8:       trying file=/usr/lib/x86_64-linux-gnu/liblibtensorflow.so
         8:       trying file=/lib/liblibtensorflow.so
         8:       trying file=/usr/lib/liblibtensorflow.so
         8:
         8:     find library=libtensorflow_framework.so [0]; searching
         8:      search path=           (RPATH from file /usr/lib/liblibtensorflow.so)
         8:      search path=/usr/lib           (system search path)
         8:       trying file=/usr/lib/libtensorflow_framework.so
         8:
         8:     find library=libcublas.so.9.0 [0]; searching
         8:      search path=           (RPATH from file /usr/lib/liblibtensorflow.so)
         8:      search path=/usr/lib           (system search path)
         8:       trying file=/usr/lib/libcublas.so.9.0
         8:      search path=../local_config_cuda/cuda/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/lib64/tls/haswell:../local_config_cuda/cuda/lib64/tls/x86_64:../local_config_cuda/cuda/lib64/tls:../local_config_cuda/cuda/lib64/haswell/x86_64:../local_config_cuda/cuda/lib64/haswell:../local_config_cuda/cuda/lib64/x86_64:../local_config_cuda/cuda/lib64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/tls:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64/haswell:../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64:../local_config_cuda/cuda/extras/CUPTI/lib64            (RPATH from file /app/runtimes/linux/native/libtensorflow.so)
         8:       trying file=../local_config_cuda/cuda/lib64/tls/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/tls/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/lib64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/tls/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/haswell/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/x86_64/libcublas.so.9.0
         8:       trying file=../local_config_cuda/cuda/extras/CUPTI/lib64/libcublas.so.9.0
         8:      search path=/usr/local/cuda-10.0/lib64         (LD_LIBRARY_PATH)
         8:       trying file=/usr/local/cuda-10.0/lib64/libcublas.so.9.0
         8:      search cache=/etc/ld.so.cache
         8:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
         8:       trying file=/lib/x86_64-linux-gnu/libcublas.so.9.0
         8:       trying file=/usr/lib/x86_64-linux-gnu/libcublas.so.9.0
         8:       trying file=/lib/libcublas.so.9.0
         8:       trying file=/usr/lib/libcublas.so.9.0
         8:
         8:     find library=libtensorflow [0]; searching
         8:      search path=/usr/local/cuda-10.0/lib64         (LD_LIBRARY_PATH)
         8:       trying file=/usr/local/cuda-10.0/lib64/libtensorflow
         8:      search cache=/etc/ld.so.cache
         8:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
         8:       trying file=/lib/x86_64-linux-gnu/libtensorflow
         8:       trying file=/usr/lib/x86_64-linux-gnu/libtensorflow
         8:       trying file=/lib/libtensorflow
         8:       trying file=/usr/lib/libtensorflow
         8:
         8:     find library=liblibtensorflow [0]; searching
         8:      search path=/usr/local/cuda-10.0/lib64         (LD_LIBRARY_PATH)
         8:       trying file=/usr/local/cuda-10.0/lib64/liblibtensorflow
         8:      search cache=/etc/ld.so.cache
         8:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
         8:       trying file=/lib/x86_64-linux-gnu/liblibtensorflow
         8:       trying file=/usr/lib/x86_64-linux-gnu/liblibtensorflow
         8:       trying file=/lib/liblibtensorflow
         8:       trying file=/usr/lib/liblibtensorflow
         8:
fail: People.Service[0]
      Unable to load shared library 'libtensorflow' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibtensorflow: cannot open shared object file: No such file or directory
System.DllNotFoundException: Unable to load shared library 'libtensorflow' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibtensorflow: cannot open shared object file: No such file or directory
   at TensorFlow.TFGraph.TF_NewGraph()
   at TensorFlow.TFGraph..ctor()
```

**Comment by turowicz** [comment]
Paging @migueldeicaza 

Do you think its possible to use the current version with CUDA10 somehow?

**Comment by turowicz** [comment]
I'm considering a manual build of v1.12.0 with CUDA10

https://www.tensorflow.org/install/source

**Comment by Jiraiyah** [comment]
> I'm having a problem when trying to run a Ubuntu+GPU solution with TensorflowSharp.
> 
> Currently it's wrapping around `libtensorflow.so` v1.12.0 which was built with `CUDA 9`. All my machines are running `CUDA 10` and I'm unable to run TensorflowSharp, because the old `.so` file is trying to find `CUDA 9` dependencies in runtime.
> 
> **Describe the solution you'd like**
> Update the wrapper to use `libtensorflow.so` v1.13.1
> 
> **Describe alternatives you've considered**
> Dropping TensorflowSharp - but I don't want to!

plus one for the update please.

**Comment by captainst** [comment]
I am not sure if v1.12.0 works with CUDA10. But definitely works with CUDA9.
A reference with WIN10 is here: https://github.com/migueldeicaza/TensorFlowSharp/issues/236#issuecomment-473336272

**Comment by Jiraiyah** [comment]
1.13.1 works with CUDA 10

**Comment by turowicz** [comment]
@Jiraiyah yes we know, hence the request to update TF# to work with 1.13.x.

**Comment by Kjos** [comment]
I'm running 1.14 and would also like to run TF# with Cuda on Windows. I guess I'll try to downgrade to CUDA 9 instead for now.

**Comment by turowicz** [comment]
@Kjos I've compiled TF 13.x manually with CUDA 10 and it works fine with TF#.

**Comment by Kjos** [comment]
@turowicz Thanks, but I already gotten it working with TF 14. There was another issue that prevented it working with 10 (setting memory allocation on GPU with TF).
